import { cva } from "class-variance-authority";

export const LoginBtn = cva([
  "button",
  "inline-flex",
  "items-center",
  "justify-center",
  "gap-2",
  "text-white",
  "font-medium",
  "bg-blue-600",
  "hover:bg-blue-600/90",
  "h-10",
  "shadow",
  "px-4",
  "py-4",
  "border",
  "rounded-md",
]);

export const langsBtn = cva([
  "langs",
  "inline-flex",
  "h-9",
  "w-9",
  "items-center",
  "justify-center",
  "gap-2",
  "whitespace-nowrap",
  "rounded-md",
  "border-0",
  "text-sm",
  "font-medium",
  "transition-none",
  "transition-colors",
  "focus-visible:outline-none",
  "focus-visible:ring-1",
  "focus-visible:ring-ring",
  "disabled:pointer-events-none",
  "hover:text-accent-foreground",
  "disabled:opacity-50",
  "[&_svg]:pointer-events-none",
  "[&_svg]:size-4",
  "[&_svg]:shrink-0",
  "hover:bg-accent",
]);

export const ThemeBtn = cva([
  "inline-flex",
  "items-center",
  "justify-center",
  "gap-2",
  "whitespace-nowrap",
  "rounded-md",
  "text-sm",
  "font-medium",
  "transition-colors",
  "focus-visible:outline-none",
  "focus-visible:ring-1",
  "focus-visible:ring-ring",
  "disabled:pointer-events-none",
  "disabled:opacity-50",
  "[&_svg]:pointer-events-none",
  "[&_svg]:size-4",
  "[&_svg]:shrink-0",
  "border",
  "border-input",
  "bg-background",
  "shadow-sm",
  "hover:bg-accent",
  "hover:text-accent-foreground",
  "h-9",
  "w-9",
]);

export const comItem = cva([
  "item_a",
  "rounded-sm",
  "bg-secondary",
  "px-2.5",
  "py-0.5",
  "text-xs",
]);

export const Author = cva([
  "author_a",
  "rounded-sm",
  "bg-transparent",
  "border",
  "px-2.5",
  "py-0.5",
  "text-xs",
]);
